/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  usms: [
    "usms/index",
    {
      type: 'category',
      label: '操作指南',
      items: [{
        type: 'autogenerated',
        dirName: 'usms/guide'
      }]
    },
    {
      type: 'category',
      label: '产品简介',
      items: [{
        type: 'autogenerated',
        dirName: 'usms/introduction'
      }]
    },
    {
      type: 'category',
      label: '审核标准',
      items: [{
        type: 'autogenerated',
        dirName: 'usms/auth_type'
      }]
    },
    {
      type: 'category',
      label: '产品定价',
      items: [{
        type: 'autogenerated',
        dirName: 'usms/price'
      }]
    },
    {
      type: 'category',
      label: '国内短信',
      items: [{
        type: 'autogenerated',
        dirName: 'usms/usage'
      }]
    },
    {
      type: 'category',
      label: '常见问题',
      items: [{
        type: 'autogenerated',
        dirName: 'usms/faq_simple'
      }]
    },
  ],
  isms: [
    "isms/index",
    {
      type: 'category',
      label: '操作指南',
      items: [{
        type: 'autogenerated',
        dirName: 'isms/get-started'
      }]
    },
  ],
  uaim: [
    {
      type: 'category',
      label: '产品简介',
      items: [{
        type: 'autogenerated',
        dirName: 'uaim/introduction'
      }]
    },
    {
      type: 'category',
      label: '操作指南',
      items: [{
        type: 'autogenerated',
        dirName: 'uaim/guide'
      }]
    },
    {
      type: 'category',
      label: '审核标准',
      items: [{
        type: 'autogenerated',
        dirName: 'uaim/examine'
      }]
    },
    {
      type: 'category',
      label: '产品定价',
      items: [{
        type: 'autogenerated',
        dirName: 'uaim/price'
      }]
    },
    // {
    //   type: 'category',
    //   label: '服务协议',
    //   items: [{
    //     type: 'autogenerated',
    //     dirName: 'uaim/agreement'
    //   }]
    // },
  ],
  // agreement: [
  //   "agreement/index",
  // ],
  // sdk: [
  //   {
  //     type: 'category',
  //     label: 'Getting Started',
  //     items: [{
  //       type: 'autogenerated',
  //       dirName: 'sdk'
  //     }]
  //   }
  // ],
  // api: [
  //   {
  //     type: 'category',
  //     label: 'API LIST',
  //     items: [{
  //       type: 'autogenerated',
  //       dirName: 'api'
  //     }]
  //   }
  // ]
};

module.exports = sidebars;