/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  usms: [
    "usms/index",
    {
      type: 'category',
      label: '操作指南',
      items: [{
        type: 'autogenerated',
        dirName: 'usms/guide'
      }]
    },
    {
      type: 'category',
      label: '产品简介',
      items: [{
        type: 'autogenerated',
        dirName: 'usms/introduction'
      }]
    },
    {
      type: 'category',
      label: '审核标准',
      items: [{
        type: 'autogenerated',
        dirName: 'usms/auth_type'
      }]
    },
    {
      type: 'category',
      label: '产品定价',
      items: [{
        type: 'autogenerated',
        dirName: 'usms/price'
      }]
    },
    {
      type: 'category',
      label: '国内短信',
      items: [{
        type: 'autogenerated',
        dirName: 'usms/usage'
      }]
    },
    // "usms/introduction",
    // {
    //   type: 'category',
    //   label: 'Getting Started',
    //   items: [{
    //     type: 'autogenerated',
    //     dirName: 'sms/started'
    //   }]
    // },
    // {
    //   type: 'category',
    //   label: 'legal',
    //   items: [{
    //     type: 'autogenerated',
    //     dirName: 'sms/legal'
    //   }]
    // }
  ],
  isms: [
    "isms/index",
    {
      type: 'category',
      label: '测试',
      items: [{
        type: 'autogenerated',
        dirName: 'isms/test'
      }]
    },
  ],
  uaim: [
    "uaim/index"
  ]
  // sdk: [
  //   {
  //     type: 'category',
  //     label: 'Getting Started',
  //     items: [{
  //       type: 'autogenerated',
  //       dirName: 'sdk'
  //     }]
  //   }
  // ],
  // api: [
  //   {
  //     type: 'category',
  //     label: 'API LIST',
  //     items: [{
  //       type: 'autogenerated',
  //       dirName: 'api'
  //     }]
  //   }
  // ]
};

module.exports = sidebars;