name: github pages

on:
  push:
    branches:
      - main # default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn install
      - name: Build website
        run: echo ${{ secrets.DOCKER_USERNAME }} && yarn build
      
      - name: Login to UHub
        uses: docker/login-action@v2
        with:
          registry: uhub.service.ucloud.cn
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        # run: |
        #  docker login uhub.service.ucloud.cn -u ${{ secrets.ACCOUNT }} -p ${{ secrets.UM_PASSWORD }}
      
      - name: Push docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          platforms: linux/amd64
          push: true
          tags: um-docs/um-product-docs:latest