name: github pages

on:
  push:
    branches:
      - main # default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn install
      - name: Build website
        run: yarn build
      
      - name: Login to UHub
        uses: docker/login-action@v2
        with:
          registry: uhub.service.ucloud.cn
          username: ${{ secrets.ACCOUNT }}
          password: ${{ secrets.UM_PASSWORD }}
      
      - name: Push docker image
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          push: true
          tags: um-product-docs:latest


      # - name: Deploy to Github Pages
        # uses: peaceiris/actions-gh-pages@v3
        # with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          # publish_dir: ./build